### PR TITLE
Made changes to avoid error I got when using .humanize() and changed …

### PR DESCRIPTION
**Pull request by mofikus**
…the date format to suit my needs (e.g 01 January 2017).

Also changed so that a number of sensors are created for the next n events. The number is set with a new configuration option for "max number of events", by default this is 5.

### CODE REVIEW

**Comment by vmtyler** [comment]
I don't understand the multiple sensors. what's the use case?

**Comment by mofikus** [comment]
In my hadashboard I have the following...

screen shot 2017-02-26 at 14 24 56

So I can see on the dashboard the next 5 events I have upcoming, which at the moment isn't many so the UK holidays are displayed. I wanted home assistant to collect all this information rather than dashing incase I decide to use something else to display information form home assistant.

**Comment by vmtyler** [comment]
ahh ok. event_0 is always the next event. I would say we should set the default # of events to 1. I use this sensor to trigger vacation lighting programs when my calendar shows I'm away.

**Comment by vmtyler** [comment]
also I think I'll make the date format configurable.

**Comment by mofikus** [comment]
Ok that makes sense. Also I think I made it so if there is no further events it will show "no event" but I've not tested how this is displayed. Making that date format configurable would be good too.

**Comment by vmtyler** [comment]
cool I'll merge this and then make those change

**Comment by mofikus** [comment]
Awesome, just tested with max events set to 5, and then only having two events in the calendar and it displays as expected.

**Pull request merged**
